### ISSUE TITLE
Change one-line description of project

### ISSUE THREAD

**Issue by vsub21** [ADI-Labs/mavi#6]
Currently is "Web app to pull data from facebook free and for sale" from marketplace days of project; need to change

**Comment by francesar** [comment]
do you guys want me to just change it to WTF Columbia? Or would you guys rather have the one liner on the README to be here

**Comment by vsub21** [comment]
IMO the one-liner of the README would probably be good with "WTF Columbia" in front of it; thoughts any one else?

**Comment by Howon** [comment]
Do both but on ur readme include how to run this webapp
